# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/https://github.com/barakdiker123/nbdev_first_project.git',
                'doc_host': 'https://barakdiker.github.io',
                'git_url': 'https://github.com/barakdiker/https://github.com/barakdiker123/nbdev_first_project.git',
                'lib_path': 'https://github.com/barakdiker123/nbdev_first_project.git'},
  'syms': {'nbdev_first_project.git.core': {'nbdev_first_project.git.core.foo': ('core.html#foo', 'nbdev_first_project.git/core.py')}}}
